### ISSUE TITLE
Unity failed

### ISSUE THREAD

**Issue by longde123** [deeparteffects/deeparteffects-api-dotnet-csharp-example#1]
SpritePacker failed to get types from RestSharp, Version=105.1.0.0, Culture=neutral, PublicKeyToken=null.
UnityEditor.Sprites.Packer:GetSelectedPolicyId()
SpritePacker failed to get types from DeepArtEffectsClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
UnityEditor.Sprites.Packer:GetSelectedPolicyId()
SpritePacker failed to get types from Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed.
UnityEditor.Sprites.Packer:GetSelectedPolicyId()

**Comment by clarrat** [comment]
Did you change the secrets in the app.config file to your values?

**Comment by clarrat** [comment]
This error has been fixed.
